name: build
on:
  push:
    branches:
      - develop
      - master
      - release-*
  pull_request:
    branches:
      - develop
      - master
      - release-*
     


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: >
            [
              {
                "id": "bar",
                "name": "Bonita Artifact Repository",
                "url": "https://bonitasoft.jfrog.io/artifactory/releases",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          plugin_repositories: >
            [
              {
                "id": "bar",
                "name": "Bonita Artifact Repository",
                "url": "https://bonitasoft.jfrog.io/artifactory/releases",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          servers: >
            [
              {
                "id": "bar",
                "username": "${{ secrets.JFROG_USER }}",
                "password": "${{ secrets.JFROG_TOKEN }}"
              }
            ]

      - name: Build
        run: ./mvnw clean package -Dbonita.environment=integration 

      - name: "Display artifacts"
        run: ls -ltr app/target      
